version: 2

docker_defaults: &docker_defaults
    docker:
        - image: cypress/base:10
          environment:
              TERM: xterm
    working_directory: ~/project/repo

attach_workspace: &attach_workspace
    attach_workspace:
        at: ~/project

install_steps: &install_steps
    steps:
        - checkout
        - restore_cache:
              name: Restore cache
              keys:
                  - cache-{{ checksum "package.json" }}
        - run:
              name: Installing Dependencies
              command: |
                  yarn install --silent --frozen-lockfile
        - save_cache:
              name: Save cache
              key: cache-{{ checksum "package.json" }}
              paths:
                  - ~/.cache
        - persist_to_workspace:
              root: ~/project
              paths:
                  - repo

workflows:
    version: 2
    build_pipeline:
        jobs:
            - build
            - unit_test:
                  requires:
                      - build
            - end_to_end:
                  requires:
                      - build
jobs:
    build:
        <<: *docker_defaults
        <<: *install_steps
    unit_test:
        <<: *docker_defaults
        steps:
            - *attach_workspace
            - run:
                  name: Running unit tests
                  command: |
                      yarn lint
                      yarn flow check --flowconfig-name=.flowconfig-ci
                      yarn test:jest
                      yarn coveralls
    end_to_end:
        <<: *docker_defaults
        <<: *install_steps
        steps:
            - *attach_workspace
            - run:
                  name: Running E2E tests
                  command: |
                      yarn e2e
